name: build-simplestreams
on:
  push:
    tags:
      - processed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download release assets
        run: |
          mkdir assets
          gh release download processed --repo oneclickvirt/lxd_images --dir assets
      - name: Generate simplestreams
        run: |
          mkdir -p public/streams/v1
          python3 << 'EOF'
import os,json,time,hashlib
assets_dir='assets'
base_url='https://lxdimages.spiritlhl.net'
images=[]
for root,dirs,files in os.walk(assets_dir):
    for f in files:
        path=os.path.join(root,f)
        rel_path=os.path.relpath(path,assets_dir).replace('\\','/')
        url=f"{base_url}/{rel_path}"
        size=os.path.getsize(path)
        h=hashlib.sha256(open(path,'rb').read()).hexdigest()
        images.append({'filename':f,'path':rel_path,'size':size,'hash':h,'url':url})
images_json={'metadata':{'timestamp':int(time.time())},'images':images}
with open('public/streams/v1/images.json','w') as ef: json.dump(images_json,ef)
index_data={'default':{'datatype':'images','path':'streams/v1/images.json','updated':time.strftime('%Y-%m-%dT%H:%M:%SZ',time.gmtime())}}
with open('public/streams/v1/index.json','w') as jf: json.dump(index_data,jf)
EOF
      - name: Add CNAME
        run: echo 'lxdimages.spiritlhl.net' > public/CNAME
      - name: Copy assets
        run: cp -r assets public/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
