name: Build Simplestreams

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build-repository:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: 获取资产信息
        run: |
          mkdir -p temp
          processed_assets=$(curl -s "https://api.github.com/repos/oneclickvirt/lxd_images/releases" | \
            jq -r '.[] | select(.tag_name=="processed") | .assets // empty')
          if [ "$processed_assets" != "null" ] && [ "$processed_assets" != "empty" ] && [ -n "$processed_assets" ]; then
            echo "$processed_assets" > temp/assets.json
          else
            echo "[]" > temp/assets.json
          fi

      - name: 处理镜像信息
        run: |
          cat > process_images.jq << 'EOF'
          [
            .[] | 
            select(.name | test("^[a-z0-9]+-[0-9a-z\\.-]+-[a-z0-9]+-[a-z]+-rootfs\\.squashfs$")) |
            {
              name: .name,
              rootfs_url: .browser_download_url,
              rootfs_size: .size,
              lxd_name: (.name | sub("-rootfs\\.squashfs$"; "-lxd.tar.xz"))
            }
          ] |
          map(
            . as $rootfs |
            ($rootfs.name | capture("^(?<os>[a-z0-9]+)-(?<version>[0-9a-z\\.-]+)-(?<arch>[a-z0-9]+)-(?<variant>[a-z]+)-rootfs\\.squashfs$")) as $parsed |
            if $parsed then
              $rootfs + $parsed + {
                lxd_info: (
                  input_filename as $assets_file |
                  $assets_file | 
                  map(select(.name == $rootfs.lxd_name)) | 
                  if length > 0 then .[0] else null end
                )
              }
            else
              empty
            end
          ) |
          map(
            select(.lxd_info != null) |
            {
              os: .os,
              version: .version,
              arch: .arch,
              variant: .variant,
              rootfs_url: .rootfs_url,
              rootfs_size: .rootfs_size,
              lxd_url: .lxd_info.browser_download_url,
              lxd_size: .lxd_info.size,
              rootfs_sha256: "unknown",
              lxd_sha256: "unknown",
              combined_sha256: "unknown"
            }
          )
          EOF
          if [ "$(jq length temp/assets.json)" -gt 0 ]; then
            jq -f process_images.jq temp/assets.json > temp/processed_images.json
          else
            echo "[]" > temp/processed_images.json
          fi

      - name: 生成 Simplestreams 结构
        run: |
          mkdir -p pages/streams/v1
          if [ "$(jq length temp/processed_images.json)" -eq 0 ]; then
            cat > pages/streams/v1/products.json << 'EOF'
          {
            "datatype": "image-downloads",
            "format": "products:1.0",
            "products": {}
          }
          EOF
            cat > pages/streams/v1/index.json << 'EOF'
          {
            "index": {
              "images": {
                "datatype": "image-downloads",
                "path": "streams/v1/products.json",
                "format": "products:1.0"
              }
            },
            "format": "index:1.0"
          }
          EOF
            exit 0
          fi
          current_time=$(date -u +"%Y%m%d_%H%M")
          jq -n --slurpfile images temp/processed_images.json --arg updated "$current_time" '
          {
            "datatype": "image-downloads", 
            "format": "products:1.0",
            "products": (
              $images[0] |
              group_by(.os) |
              map({
                key: .[0].os,
                value: {
                  "arch": (map(.arch) | unique | sort),
                  "release": .[0].os,
                  "os": .[0].os,
                  "versions": (
                    group_by(.version) |
                    map({
                      key: .[0].version,
                      value: {
                        "items": (
                          group_by(.arch) |
                          map({
                            key: .[0].arch,
                            value: (
                              group_by(.variant) |
                              map({
                                key: .[0].variant,
                                value: {
                                  "ftype": "squashfs",
                                  "os": .[0].os,
                                  "release": .[0].version,
                                  "version": .[0].version,
                                  "arch": .[0].arch,
                                  "variant": .[0].variant,
                                  "combined_sha256": .[0].combined_sha256,
                                  "path": ("images/" + .[0].os + "/" + .[0].version + "/" + .[0].arch + "/" + .[0].variant + "/"),
                                  "versions": {
                                    ($updated): {
                                      "items": {
                                        "lxd.tar.xz": {
                                          "ftype": "lxd.tar.xz",
                                          "size": .[0].lxd_size,
                                          "sha256": .[0].lxd_sha256,
                                          "path": ("redirect/lxd/" + (.[0].lxd_url | @uri))
                                        },
                                        "rootfs.squashfs": {
                                          "ftype": "squashfs", 
                                          "size": .[0].rootfs_size,
                                          "sha256": .[0].rootfs_sha256,
                                          "path": ("redirect/rootfs/" + (.[0].rootfs_url | @uri))
                                        }
                                      }
                                    }
                                  }
                                }
                              }) |
                              from_entries
                            )
                          }) |
                          from_entries
                        )
                      }
                    }) |
                    from_entries
                  )
                }
              }) |
              from_entries
            )
          }' > pages/streams/v1/products.json
          cat > pages/streams/v1/index.json << 'EOF'
          {
            "index": {
              "images": {
                "datatype": "image-downloads",
                "path": "streams/v1/products.json",
                "format": "products:1.0"
              }
            },
            "format": "index:1.0"
          }
          EOF

      - name: 创建重定向处理器
        run: |
          mkdir -p pages/redirect/{lxd,rootfs}
          generate_redirect_page() {
            local url="$1"
            local filename="$2"
            cat > "$filename" << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="refresh" content="0; url=$url">
            <meta name="robots" content="noindex">
            <title>Redirecting...</title>
          </head>
          <body>
            <p>Redirecting to <a href="$url">$url</a>...</p>
            <script>window.location.href = "$url";</script>
          </body>
          </html>
          EOF
          }
          if [ -f temp/processed_images.json ]; then
            jq -r '.[] | @base64' temp/processed_images.json | while IFS= read -r line; do
              decoded=$(echo "$line" | base64 -d)
              lxd_url=$(echo "$decoded" | jq -r '.lxd_url')
              rootfs_url=$(echo "$decoded" | jq -r '.rootfs_url')
              lxd_encoded=$(echo "$lxd_url" | sed 's|:|%3A|g; s|/|%2F|g; s|?|%3F|g; s|&|%26|g')
              rootfs_encoded=$(echo "$rootfs_url" | sed 's|:|%3A|g; s|/|%2F|g; s|?|%3F|g; s|&|%26|g')
              generate_redirect_page "$lxd_url" "pages/redirect/lxd/$lxd_encoded"
              generate_redirect_page "$rootfs_url" "pages/redirect/rootfs/$rootfs_encoded"
            done
          fi

      - name: 生成网页界面
        run: |
          curl -sL https://raw.githubusercontent.com/spiritLHLS/lxd-images-frontend/main/index.html -o pages/index.html
          echo "lxdimages.spiritlhl.net" >> pages/CNAME

      - name: 验证生成的文件
        run: |
          if [ -f pages/streams/v1/products.json ]; then
            echo "✅ products.json 已生成"
            echo "产品数量: $(jq '.products | length' pages/streams/v1/products.json)"
            echo "产品列表: $(jq -r '.products | keys[]' pages/streams/v1/products.json | tr '\n' ', ' | sed 's/,$//')"
          else
            echo "❌ products.json 未生成"
          fi
          if [ -f pages/streams/v1/index.json ]; then
            echo "✅ index.json 已生成"
          else
            echo "❌ index.json 未生成"
          fi
          echo "LXD 重定向文件: $(find pages/redirect/lxd -type f 2>/dev/null | wc -l)"
          echo "Rootfs 重定向文件: $(find pages/redirect/rootfs -type f 2>/dev/null | wc -l)"
          if [ -f pages/streams/v1/products.json ] && [ "$(jq '.products | length' pages/streams/v1/products.json)" -gt 0 ]; then
            jq -r '.products | to_entries | .[0] | "示例产品: \(.key)"' pages/streams/v1/products.json
          fi

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages
          publish_branch: gh-pages
          force_orphan: true
          cname: true
