name: Build Simplestreams and Deploy Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 获取 Releases 文件列表
        id: get_assets
        run: |
          API_URL="https://api.github.com/repos/oneclickvirt/lxd_images/releases/tags/processed"
          curl -sSL $API_URL > release.json
          jq -r '.assets[] | [.name, .browser_download_url] | @tsv' release.json > assets.tsv

      - name: 安装 jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: 构建 simplestreams 数据
        run: |
          mkdir -p gh-pages/streams/v1/images
          INDEX_JSON="gh-pages/streams/v1/index.json"
          IMAGES_JSON="gh-pages/streams/v1/images.json"
          echo '{ "index": [ { "path": "streams/v1/images.json", "products": {} } ] }' > "$INDEX_JSON"
          echo '{ "images": {}}' > "$IMAGES_JSON"
          while IFS=$'\t' read -r name url; do
            ext="${name##*.}"
            base="${name%.*}"
            [[ "$ext" == "tar" ]] && continue
            if [[ "$ext" == "xz" || "$ext" == "gz" || "$ext" == "zst" ]]; then
              img_name="${base%.*}"
              format="$ext"
              img_entry=$(jq -n \
                --arg name "$img_name" \
                --arg url "$url" \
                --arg format "$format" \
                --arg file "$name" \
                '{'"\"$img_name\"": {
                  "aliases": [],
                  "ftype": $format,
                  "path": $file,
                  "download_url": $url,
                  "sha256": "",
                  "size": 0,
                  "uploaded": "",
                  "auto_update": false
                }}')
              jq ".images += $img_entry" "$IMAGES_JSON" > tmp.json && mv tmp.json "$IMAGES_JSON"
              curl -sSL "$url" -o "gh-pages/streams/v1/images/$name"
            fi
          done < assets.tsv

      - name: 生成前端 index.html
        run: |
          cat > gh-pages/index.html <<EOF
          <!DOCTYPE html>
          <html lang="zh">
          <head>
            <meta charset="UTF-8">
            <title>LXD Simplestreams 镜像源</title>
          </head>
          <body>
            <h1>LXD 镜像源 - lxdimages.spiritlhl.net</h1>
            <p>作为 LXD Simplestreams 镜像源，可直接通过 <code>https://lxdimages.spiritlhl.net/streams/v1/</code> 远程添加。</p>
            <h2>文件列表</h2>
            <ul>
          EOF
          while IFS=$'\t' read -r name url; do
            echo "<li><a href=\"streams/v1/images/$name\">$name</a></li>" >> gh-pages/index.html
          done < assets.tsv
          echo "</ul></body></html>" >> gh-pages/index.html

      - name: 配置自定义域名
        run: |
          echo "lxdimages.spiritlhl.net" > gh-pages/CNAME

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          publish_branch: gh-pages
