name: Build and Deploy SimpleStreams Index to Netlify

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install requests jinja2 pyyaml
          
      - name: Generate SimpleStreams
        run: |
          python3 << 'EOF'
          import requests
          import json
          import hashlib
          import os
          from datetime import datetime, timezone
          
          GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN', '')
          REPO = 'oneclickvirt/lxd_images'
          TAG = 'processed'
          BASE_URL = f'https://github.com/{REPO}/releases/download/{TAG}'
          
          headers = {}
          if GITHUB_TOKEN:
              headers['Authorization'] = f'token {GITHUB_TOKEN}'
              
          response = requests.get(f'https://api.github.com/repos/{REPO}/releases/tags/{TAG}', headers=headers)
          if response.status_code != 200:
              print(f"Error: {response.status_code}")
              exit(1)
              
          release_data = response.json()
          assets = release_data.get('assets', [])
          
          def parse_filename(filename):
              if filename.endswith('-lxd.tar.xz'):
                  base_name = filename.replace('-lxd.tar.xz', '')
              elif filename.endswith('-rootfs.squashfs'):
                  base_name = filename.replace('-rootfs.squashfs', '')
              else:
                  return None, None, None, None
              
              parts = base_name.split('-')
              if len(parts) >= 4:
                  return parts[0], parts[1], parts[2], parts[3]
              return None, None, None, None
          
          def get_placeholder_sha256():
              return hashlib.sha256(b'placeholder').hexdigest()
          
          products = {}
          redirects_rules = []
          
          lxd_files = [asset for asset in assets if asset['name'].endswith('-lxd.tar.xz')]
          rootfs_files = [asset for asset in assets if asset['name'].endswith('-rootfs.squashfs')]
          
          current_time = datetime.now(timezone.utc)
          version_id = current_time.strftime('%Y%m%d')
          
          print(f"Processing {len(lxd_files)} LXD files")
          
          for lxd_asset in lxd_files:
              distro, version, arch, variant = parse_filename(lxd_asset['name'])
              if not all([distro, version, arch, variant]):
                  continue
                  
              rootfs_name = lxd_asset['name'].replace('-lxd.tar.xz', '-rootfs.squashfs')
              rootfs_asset = next((a for a in rootfs_files if a['name'] == rootfs_name), None)
              
              if not rootfs_asset:
                  continue
              
              # 重定向规则
              redirects_rules.append(f'/download/{lxd_asset["name"]} {BASE_URL}/{lxd_asset["name"]} 302')
              redirects_rules.append(f'/download/{rootfs_asset["name"]} {BASE_URL}/{rootfs_asset["name"]} 302')
              
              # 修复：使用标准的产品命名格式
              if variant == 'default':
                  product_name = f'{distro}:{version}:{arch}'
              else:
                  product_name = f'{distro}:{version}:{arch}:{variant}'
              
              if product_name not in products:
                  # 修复：简化别名结构，确保兼容性
                  aliases = []
                  
                  # 基础别名
                  if arch == 'amd64':
                      aliases.extend([
                          f'{distro}/{version}',
                          f'{distro}/{version}/default' if variant == 'default' else f'{distro}/{version}/{variant}'
                      ])
                  else:
                      aliases.extend([
                          f'{distro}/{version}/{arch}',
                          f'{distro}/{version}/{arch}/default' if variant == 'default' else f'{distro}/{version}/{arch}/{variant}'
                      ])
                  
                  # 去重
                  aliases = list(set(aliases))
                  
                  products[product_name] = {
                      'aliases': ','.join(aliases),
                      'arch': arch,
                      'os': distro,
                      'release': version,
                      'versions': {}
                  }
                  
                  if variant != 'default':
                      products[product_name]['variant'] = variant
              
              # 修复：使用正确的文件类型映射
              items = {
                  'lxd.tar.xz': {
                      'ftype': 'lxd.tar.xz',
                      'size': lxd_asset.get('size', 0),
                      'path': f'download/{lxd_asset["name"]}',
                      'sha256': get_placeholder_sha256()
                  }
              }
              
              # 修复：保持原始文件类型
              if rootfs_asset['name'].endswith('.squashfs'):
                  items['squashfs'] = {
                      'ftype': 'squashfs',
                      'size': rootfs_asset.get('size', 0),
                      'path': f'download/{rootfs_asset["name"]}',
                      'sha256': get_placeholder_sha256()
                  }
              
              version_data = {
                  'items': items
              }
              
              products[product_name]['versions'][version_id] = version_data
              
              print(f"Added: {product_name} with aliases: {','.join(aliases)}")
          
          current_time_str = current_time.strftime('%a, %d %b %Y %H:%M:%S +0000')
          
          # 标准 SimpleStreams 索引结构
          index_data = {
              'format': 'index:1.0',
              'index': {
                  'images': {
                      'datatype': 'image-downloads',
                      'path': 'streams/v1/images.json',
                      'updated': current_time_str,
                      'format': 'products:1.0'
                  }
              },
              'updated': current_time_str
          }
          
          # 标准 SimpleStreams 图像数据结构
          images_data = {
              'content_id': 'images',
              'datatype': 'image-downloads', 
              'format': 'products:1.0',
              'products': products,
              'updated': current_time_str
          }
          
          os.makedirs('build/streams/v1', exist_ok=True)
          
          with open('build/streams/v1/index.json', 'w') as f:
              json.dump(index_data, f, indent=2, sort_keys=True)
              
          with open('build/streams/v1/images.json', 'w') as f:
              json.dump(images_data, f, indent=2, sort_keys=True)
          
          # _redirects文件
          with open('build/_redirects', 'w') as f:
              for rule in redirects_rules:
                  f.write(rule + '\n')
              f.write('/* /index.html 200\n')
          
          print(f"Generated {len(products)} products")
          
          # 调试输出
          print("\n=== Debug Info ===")
          for product_name, product in list(products.items())[:3]:
              print(f"Product: {product_name}")
              print(f"  Aliases: {product['aliases']}")
              print(f"  Versions: {list(product['versions'].keys())}")
              if product['versions']:
                  version_key = list(product['versions'].keys())[0]
                  print(f"  Items: {list(product['versions'][version_key]['items'].keys())}")
          
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create HTML
        run: |
          cat > build/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>LXD Images Repository</title>
              <style>
                  body { font-family: Arial, sans-serif; padding: 20px; }
                  pre { background: #f0f0f0; padding: 15px; border-radius: 5px; }
                  .command { color: #0066cc; }
              </style>
          </head>
          <body>
              <h1>LXD Images Repository</h1>
              <p>SimpleStreams compatible image repository</p>
              
              <h2>Setup</h2>
              <pre class="command">lxc remote add spiritlhl https://lxdimages.spiritlhl.net --protocol simplestreams --public</pre>
              
              <h2>Usage Examples</h2>
              <pre class="command">
          # List available images
          lxc image list spiritlhl:
          
          # Launch containers
          lxc launch spiritlhl:debian/11 my-debian
          lxc launch spiritlhl:ubuntu/22.04 my-ubuntu
              </pre>
              
              <h2>API Endpoints</h2>
              <ul>
                  <li><a href="streams/v1/index.json">SimpleStreams Index</a></li>
                  <li><a href="streams/v1/images.json">Images Metadata</a></li>
              </ul>
          </body>
          </html>
          EOF
          
      - name: Create netlify.toml
        run: |
          cat > build/netlify.toml << 'EOF'
          [build]
            publish = "."
          
          [[headers]]
            for = "/streams/v1/*"
            [headers.values]
              Content-Type = "application/json; charset=utf-8"
              Cache-Control = "public, max-age=300"
              Access-Control-Allow-Origin = "*"
              Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
          
          [[headers]]
            for = "/download/*"
            [headers.values]
              Cache-Control = "public, max-age=86400"
          EOF

      - name: Deploy to Netlify  
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './build'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
