name: Update Simplestreams Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Download release assets
      run: |
        cd gh-pages
        rm -rf streams
        pip install requests
        python -c "
import requests
tag = 'processed'
owner = 'oneclickvirt'
repo = 'lxd_images'
release_url = f'https://api.github.com/repos/{owner}/{repo}/releases/tags/{tag}'
release = requests.get(release_url).json()
for asset in release['assets']:
    url = asset['browser_download_url']
    path = asset['name']
    print(f'Downloading {path}')
    r = requests.get(url)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'wb') as f:
        f.write(r.content)
        "

    - name: Generate CNAME
      run: |
        cd gh-pages
        echo 'lxdimages.spiritlhl.net' > CNAME

    - name: Generate index.html
      run: |
        cd gh-pages
        cat > index.html <<EOF
        <!DOCTYPE html>
        <html>
        <head>
            <title>LXD Image Repository</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                h1, h2 { color: #333; }
                pre { background: #f4f4f4; padding: 10px; border-radius: 5px; }
                a { color: #0366d6; }
            </style>
        </head>
        <body>
            <h1>LXD Image Repository</h1>
            <p>Simplestreams service URL: <code>https://lxdimages.spiritlhl.net/streams/v1</code></p>
            
            <h2>Usage</h2>
            <pre>lxc remote add images https://lxdimages.spiritlhl.net --protocol=simplestreams</pre>
            
            <h2>Endpoints</h2>
            <ul>
                <li><a href="/streams/v1/index.json">index.json</a></li>
                <li><a href="/streams/v1/images.json">images.json</a></li>
            </ul>
        </body>
        </html>
        EOF

    - name: Commit changes
      run: |
        cd gh-pages
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Auto-update from release"
        git push
