name: Build and Deploy SimpleStreams Index to Netlify

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install requests jinja2 pyyaml
          
      - name: Generate SimpleStreams index
        run: |
          python3 << 'EOF'
          import requests
          import json
          import hashlib
          import os
          from datetime import datetime, timezone
          
          GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN', '')
          REPO = 'oneclickvirt/lxd_images'
          TAG = 'processed'
          BASE_URL = f'https://github.com/{REPO}/releases/download/{TAG}'
          
          headers = {}
          if GITHUB_TOKEN:
              headers['Authorization'] = f'token {GITHUB_TOKEN}'
              
          response = requests.get(f'https://api.github.com/repos/{REPO}/releases/tags/{TAG}', headers=headers)
          if response.status_code != 200:
              print(f"Error: {response.status_code}")
              exit(1)
              
          release_data = response.json()
          assets = release_data.get('assets', [])
          
          def parse_filename(filename):
              if filename.endswith('-lxd.tar.xz'):
                  base_name = filename.replace('-lxd.tar.xz', '')
              elif filename.endswith('-rootfs.squashfs'):
                  base_name = filename.replace('-rootfs.squashfs', '')
              else:
                  return None, None, None, None
              
              parts = base_name.split('-')
              if len(parts) >= 4:
                  return parts[0], parts[1], parts[2], parts[3]
              return None, None, None, None
          
          # 使用占位符SHA256 - 这是关键修复
          def get_placeholder_sha256():
              return hashlib.sha256(b'placeholder').hexdigest()
          
          products = {}
          redirects_rules = []
          
          lxd_files = [asset for asset in assets if asset['name'].endswith('-lxd.tar.xz')]
          rootfs_files = [asset for asset in assets if asset['name'].endswith('-rootfs.squashfs')]
          
          current_time = datetime.now(timezone.utc)
          version_id = current_time.strftime('%Y%m%d_%H%M')
          
          print(f"Processing {len(lxd_files)} LXD files")
          
          for lxd_asset in lxd_files:
              distro, version, arch, variant = parse_filename(lxd_asset['name'])
              if not all([distro, version, arch, variant]):
                  continue
                  
              rootfs_name = lxd_asset['name'].replace('-lxd.tar.xz', '-rootfs.squashfs')
              rootfs_asset = next((a for a in rootfs_files if a['name'] == rootfs_name), None)
              
              if not rootfs_asset:
                  continue
              
              # 重定向规则
              redirects_rules.append(f'/download/{lxd_asset["name"]} {BASE_URL}/{lxd_asset["name"]} 302')
              redirects_rules.append(f'/download/{rootfs_asset["name"]} {BASE_URL}/{rootfs_asset["name"]} 302')
              
              product_name = f'{distro}:{version}:{arch}:{variant}'
              
              if product_name not in products:
                  # 关键修复：正确的别名格式
                  aliases = [
                      f'{distro}/{version}',
                      f'{distro}/{version}/{arch}',
                      f'{distro}:{version}:{arch}'
                  ]
                  
                  if variant != 'default':
                      aliases.append(f'{distro}/{version}/{arch}/{variant}')
                  
                  products[product_name] = {
                      'aliases': aliases,  # 直接使用字符串数组，不是对象数组
                      'arch': arch,
                      'os': distro,
                      'release': version,
                      'variant': variant,
                      'versions': {}
                  }
              
              products[product_name]['versions'][version_id] = {
                  'items': {
                      'lxd.tar.xz': {
                          'ftype': 'lxd.tar.xz',
                          'size': lxd_asset.get('size', 0),
                          'path': f'download/{lxd_asset["name"]}',
                          'sha256': get_placeholder_sha256()  # 使用占位符
                      },
                      'rootfs.squashfs': {
                          'ftype': 'squashfs',
                          'size': rootfs_asset.get('size', 0),
                          'path': f'download/{rootfs_asset["name"]}',
                          'sha256': get_placeholder_sha256()  # 使用占位符
                      }
                  }
              }
              
              print(f"Added: {product_name}")
          
          current_time_str = current_time.strftime('%a, %d %b %Y %H:%M:%S +0000')
          
          # SimpleStreams索引
          index_data = {
              'format': 'index:1.0',
              'index': {
                  'images': {
                      'datatype': 'image-downloads',
                      'path': 'streams/v1/images.json',
                      'updated': current_time_str,
                      'products': list(products.keys()),
                      'format': 'products:1.0'
                  }
              },
              'updated': current_time_str
          }
          
          images_data = {
              'content_id': 'images',
              'datatype': 'image-downloads',
              'format': 'products:1.0',
              'products': products,
              'updated': current_time_str
          }
          
          os.makedirs('build/streams/v1', exist_ok=True)
          
          with open('build/streams/v1/index.json', 'w') as f:
              json.dump(index_data, f, indent=2)
              
          with open('build/streams/v1/images.json', 'w') as f:
              json.dump(images_data, f, indent=2)
          
          # _redirects文件
          with open('build/_redirects', 'w') as f:
              for rule in redirects_rules:
                  f.write(rule + '\n')
              f.write('/* /index.html 200\n')
          
          print(f"Generated {len(products)} products with {len(redirects_rules)} redirects")
          
          # 验证别名
          print("\n=== 验证别名 ===")
          for product_name, product in products.items():
              if product['os'] == 'debian' and product['release'] == '11':
                  print(f"Debian 11 aliases: {product['aliases']}")
          
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create simple HTML
        run: |
          cat > build/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>LXD Images</title>
          </head>
          <body>
              <h1>LXD Images Repository</h1>
              <p>Add this remote: <code>lxc remote add spiritlhl https://lxdimages.spiritlhl.net --protocol simplestreams --public</code></p>
              <p><a href="streams/v1/index.json">Index</a> | <a href="streams/v1/images.json">Images</a></p>
          </body>
          </html>
          EOF
          
      - name: Create netlify.toml
        run: |
          cat > build/netlify.toml << 'EOF'
          [build]
            publish = "."
          
          [[headers]]
            for = "/streams/v1/*"
            [headers.values]
              Content-Type = "application/json"
              Cache-Control = "max-age=300"
              Access-Control-Allow-Origin = "*"
          EOF

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './build'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
