name: Build & Deploy Simplestreams from GitHub Releases

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python for fetching Release assets & generating tree.yml + ssb.json files
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install requests pyyaml

      # 4. Fetch Release assets, generate per-product ssb.json + tree.yml
      - name: Generate inputs for simplestreams-builder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 << 'EOF'
          import os, requests, json, yaml, hashlib
          from datetime import datetime, timezone

          # --- Configuration ---
          GITHUB_TOKEN = os.getenv('GITHUB_TOKEN', '')
          REPO = 'oneclickvirt/lxd_images'
          TAG = 'processed'
          BASE_URL = f'https://github.com/{REPO}/releases/download/{TAG}'
          PREFIX = ""
          IMAGES_PATH = "streams/v1"
          DATATYPE = "image-downloads"
          FORMAT = "products:1.0"

          # --- Helper functions ---
          def parse_filename(name):
              # expected: os-release-arch-variant-lxd.tar.xz / -rootfs.squashfs
              base = (name[:-11] if name.endswith('-lxd.tar.xz') else
                      name[:-15] if name.endswith('-rootfs.squashfs') else None)
              if not base:
                  return None
              parts = base.split('-')
              if len(parts) < 4:
                  return None
              return {
                  'os': parts[0],
                  'release': parts[1],
                  'arch': parts[2],
                  'variant': parts[3],
                  'name': base
              }

          def sha256_placeholder():
              return hashlib.sha256(b'placeholder').hexdigest()

          # --- Fetch release data ---
          headers = {'Authorization': f'token {GITHUB_TOKEN}'} if GITHUB_TOKEN else {}
          resp = requests.get(f'https://api.github.com/repos/{REPO}/releases/tags/{TAG}', headers=headers)
          resp.raise_for_status()
          assets = resp.json().get('assets', [])

          # --- Build product entries and ssb.json files ---
          products = []
          timestamp = datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')

          # group LXD & rootfs assets
          lxd_assets = [a for a in assets if a['name'].endswith('-lxd.tar.xz')]
          rootfs_assets = {a['name']: a for a in assets if a['name'].endswith('-rootfs.squashfs')}

          for lxd in lxd_assets:
              info = parse_filename(lxd['name'])
              if not info:
                  continue
              root_name = lxd['name'].replace('-lxd.tar.xz', '-rootfs.squashfs')
              root = rootfs_assets.get(root_name)
              if not root:
                  continue

              # determine product directory: os/release/arch[/variant]
              variant = info['variant']
              parts = [info['os'], info['release'], info['arch']]
              if variant != 'default':
                  parts.append(variant)
              directory = os.path.join(*parts)

              os.makedirs(directory, exist_ok=True)

              # create ssb.json
              ssb = {
                  "version": timestamp,
                  "items": {
                      "lxd.tar.xz": {
                          "size": lxd.get('size', 0),
                          "path": f"download/{lxd['name']}",
                          "sha256": sha256_placeholder()
                      },
                      "rootfs.squashfs": {
                          "size": root.get('size', 0),
                          "path": f"download/{root['name']}",
                          "sha256": sha256_placeholder()
                      }
                  }
              }
              with open(f"{directory}/ssb.json", "w") as f:
                  json.dump(ssb, f, indent=2, sort_keys=True)

              # build aliases list
              aliases = []
              base_alias = f"{info['os']}/{info['release']}"
              if info['arch'] != 'amd64':
                  base_alias += f"/{info['arch']}"
              aliases.append(base_alias)
              if variant != 'default':
                  aliases.append(base_alias + f"/{variant}")

              products.append({
                  "name": info['name'] + (f"-{variant}" if variant != 'default' else ''),
                  "os": info['os'],
                  "arch": info['arch'],
                  "release": info['release'],
                  "release_title": f"{info['os'].title()} {info['release']}",
                  "directory": directory.replace("\\","/"),
                  "days": 1,
                  "aliases": aliases
              })

          # --- Generate tree.yml ---
          tree = {
              "prefix": PREFIX,
              "images_path": IMAGES_PATH,
              "datatype": DATATYPE,
              "format": FORMAT,
              "products": products
          }
          with open("tree.yml", "w") as f:
              yaml.safe_dump(tree, f, sort_keys=False)
          EOF

      # 5. Install Go & simplestreams-builder
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install simplestreams-builder
        run: |
          go install github.com/MottainaiCI/simplestreams-builder@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      # 6. Run simplestreams-builder to produce images.json & index.json
      - name: Build images.json
        run: |
          simplestreams-builder build-images-file --config tree.yml

      - name: Build index.json
        run: |
          simplestreams-builder build-index --config tree.yml

      # 7. Create a simple HTML landing page
      - name: Create index.html
        run: |
          mkdir -p build
          cat > build/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head><meta charset="utf-8"><title>LXD SimpleStreams</title></head>
          <body>
            <h1>GitHub Release–based SimpleStreams</h1>
            <pre><code>lxc remote add spiritlhl https://${
              { secrets.NETLIFY_SITE_ID } }/ --protocol simplestreams --public</code></pre>
            <ul>
              <li><a href="streams/v1/index.json">Index</a></li>
              <li><a href="streams/v1/images.json">Images</a></li>
            </ul>
          </body>
          </html>
          EOF

      # 8. Generate Netlify config
      - name: Create netlify.toml
        run: |
          cat > netlify.toml << 'EOF'
          [build]
            publish = "build"

          [[headers]]
            for = "/streams/v1/*"
            [headers.values]
              Content-Type = "application/json; charset=utf-8"
              Cache-Control = "public, max-age=300"
              Access-Control-Allow-Origin = "*"
              Access-Control-Allow-Methods = "GET, HEAD"

          [[headers]]
            for = "/download/*"
            [headers.values]
              Cache-Control = "public, max-age=86400"
          EOF

      # 9. Deploy to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './build'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
